---
services:
  pihole:
    container_name: pihole
    hostname: pihole.copilot
    image: pihole/pihole:latest
    environment:
      WEBTHEME: default-dark
      TZ: Europe/London
      WEBPASSWORD: Szxs234.
    volumes:
      - /opt/appdata/pihole:/etc/pihole/
      - /opt/appdata/pihole/dnsmasq:/etc/dnsmasq.d/
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 80:80/tcp
    cap_add:
      - NET_ADMIN
    restart: always
    networks:
      - frontend

  homepage:
    container_name: homepage
    hostname: homepage
    image: ghcr.io/gethomepage/homepage:latest
    environment:
      PUID: $PUID
      PGID: $PGID
    volumes:
      - /opt/appdata/homepage:/app/config
      - /var/run/docker.sock:/var/run/docker.sock:ro
    env_file: /opt/copilot/.env
#    labels:
#      - "traefik.enable=true"
#      - "traefik.http.routers.homepage.rule=Host(`homepage.cityplug.io`)"
#      - "traefik.http.routers.homepage.entrypoints=websecure"
#      - "traefik.http.routers.homepage.tls=true"
#      - "traefik.http.routers.homepage.tls.certresolver=copilot"
    ports:
      - 85:3000
    restart: unless-stopped
    networks:
      - frontend
      - backend

networks:
  frontend:
    external: true
  backend:
    external: true